spring.application.name=FinalProject
server.port=9000

# oracle DataSource Setting ( Connection Pool )
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# 로컬
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=ACORNFINAL
#spring.datasource.password=ACORNFINAL

# 공통 
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=kwak
spring.datasource.password=acorn

# spring devtools 가 서버를 restart 할때 모든 classpath 를 검색하도록 classpath*
mybatis.mapper-locations=classpath*:mapper/*.xml
# type 에 별칭을 붙인 클래스를 찾아서 로딩하기 위해 
mybatis.type-aliases-package=com.example.FinalProject.**
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# MyBatis 설정
mybatis.configuration.map-underscore-to-camel-case=true

# file size, request size setting
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB